apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: chatapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: jawadahmad68/chatapp-backend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5001
        env:
        - name: MONGODB_URI
          valueFrom:
            secretKeyRef:
              name: chatapp-secret
              key: MONGODB_URI
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: chatapp-secret
              key: JWT_SECRET
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: chatapp-config
              key: PORT
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: chatapp-config
              key: NODE_ENV
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
