services:
  backend:
    build: ./backend
    ports:
      - "5000:5001"
    environment:
      MONGODB_URI: mongodb://admin:admin123@mongo:27017/chatapp?authSource=admin
      JWT_SECRET: your_jwt_secret_key
      PORT: 5001
      NODE_ENV: production
    depends_on:
      mongo:
        condition: service_started

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      backend:
        condition: service_started

  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
    volumes:
      - mongo_data:/data/db

  mongo-express:
    image: mongo-express
    ports:
      - "8081:8081"
    depends_on:
      mongo:
        condition: service_started
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin123
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin123
    restart: always

volumes:
  mongo_data:
