apiVersion: v1
kind: ConfigMap
metadata:
  name: chatapp-config
  namespace: chatapp
data:
  PORT: "5001"
  NODE_ENV: "production"
  ME_CONFIG_MONGODB_SERVER: "mongo"
  ME_CONFIG_MONGODB_PORT: "27017"
